### ISSUE TITLE
How run project in local?

### ISSUE THREAD

**Issue by DayronDLR** [eclipse-sprotty/sprotty-vscode#82]
Is it possible to run the project locally? I would like to integrate a DSL with Sprotty, Theia and Xtext, but I can't find a stable project that at least runs locally...

**Comment by spoenemann** [comment]
Yes, this repo includes an example for Sprotty + Xtext as VS Code extension, which can also be used in Theia. It's not possible to include a language server directly in Theia, so you have to go the VS Code extension way for that.

Have you considered using Langium (https://langium.org/) instead of Xtext?

**Comment by DayronDLR** [comment]
The DSL I have is written in Xtext, so I need to create a graphical environment for it. With this project, how do you prove that the extension is looking good? Because I don't understand how they debug locally.

**Comment by spoenemann** [comment]
The Xtext language server is built with Gradle and needs to be built before `yarn` is called. The yarn build copies the Gradle build result into the VS Code extension folder. To debug such a language server running in Java, you need to connect to the Java process via remote debugging. Alternatively, you can use the SocketServerLauncher offered by Xtext and connect to it in the extension code with a local socket.
